# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traukinys.ui'
#
# Created: Sat Apr 27 18:14:01 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Traukinys(object):
    def setupUi(self, Traukinys):
        Traukinys.setObjectName("Traukinys")
        Traukinys.setEnabled(False)
        Traukinys.resize(326, 281)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Traukinys.sizePolicy().hasHeightForWidth())
        Traukinys.setSizePolicy(sizePolicy)
        Traukinys.setMinimumSize(QtCore.QSize(326, 280))
        Traukinys.setAutoFillBackground(True)
        self.lSpeed = QtGui.QLabel(Traukinys)
        self.lSpeed.setGeometry(QtCore.QRect(200, 120, 111, 20))
        self.lSpeed.setStyleSheet("font: 75 italic 12pt sans;")
        self.lSpeed.setObjectName("lSpeed")
        self.label_3 = QtGui.QLabel(Traukinys)
        self.label_3.setGeometry(QtCore.QRect(0, 50, 66, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(Traukinys)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 141, 31))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.bStabis = QtGui.QPushButton(Traukinys)
        self.bStabis.setGeometry(QtCore.QRect(190, 200, 81, 71))
        self.bStabis.setObjectName("bStabis")
        self.dGreitis = QtGui.QDial(Traukinys)
        self.dGreitis.setGeometry(QtCore.QRect(10, 120, 161, 151))
        self.dGreitis.setStyleSheet("background: rgba(0, 25, 255, 128)")
        self.dGreitis.setMinimum(-100)
        self.dGreitis.setMaximum(100)
        self.dGreitis.setSingleStep(1)
        self.dGreitis.setWrapping(False)
        self.dGreitis.setNotchesVisible(True)
        self.dGreitis.setObjectName("dGreitis")
        self.label = QtGui.QLabel(Traukinys)
        self.label.setGeometry(QtCore.QRect(200, 80, 111, 41))
        self.label.setStyleSheet("font: 75 italic 20pt sans;")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.pSignalas = QtGui.QProgressBar(Traukinys)
        self.pSignalas.setGeometry(QtCore.QRect(70, 50, 161, 23))
        self.pSignalas.setMinimum(-91)
        self.pSignalas.setMaximum(0)
        self.pSignalas.setProperty("value", -90)
        self.pSignalas.setObjectName("pSignalas")
        self.label_5 = QtGui.QLabel(Traukinys)
        self.label_5.setGeometry(QtCore.QRect(110, 100, 66, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(Traukinys)
        self.label_6.setGeometry(QtCore.QRect(30, 100, 51, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line = QtGui.QFrame(Traukinys)
        self.line.setGeometry(QtCore.QRect(310, 10, 20, 301))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Traukinys)
        QtCore.QMetaObject.connectSlotsByName(Traukinys)

    def retranslateUi(self, Traukinys):
        Traukinys.setWindowTitle(QtGui.QApplication.translate("Traukinys", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lSpeed.setText(QtGui.QApplication.translate("Traukinys", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Traukinys", "Signalas:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Traukinys", "<html><head/><body><p><span style=\" font-size:14pt;\">Traukinys:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.bStabis.setText(QtGui.QApplication.translate("Traukinys", "STABDIS", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Traukinys", "Greitis:", None, QtGui.QApplication.UnicodeUTF8))
        self.pSignalas.setFormat(QtGui.QApplication.translate("Traukinys", "%v dBm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Traukinys", "Pirmyn", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Traukinys", "Atgal", None, QtGui.QApplication.UnicodeUTF8))

